spring.application.name=POVA
openai.api.key=************************YR3yjuXkfTpIHWrKBT2WNtmVExWAD6zxZUJ3DPB7x9U7jfKcdaGVaY5aWk4nuidB89X2z12CT3BlbkFJvDXjYfP-oU2EEc4bQSJrkcQKYy7MDtyrJdeITZcLKYvFKOKS3Z3qkqBzNXrsSl606CWoGAAcIA
openai.base.url=https://api.openai.com/v1/chat/completions
# Model config
GEMINI_API_KEY=*************CwDuKC5ziBtZrgxRJnzF2KlB9og_**********************




spring.ai.google.genai.chat.options.model=gemini-2.5-flash 
#spring.ai.google.genai.location==us-central1
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
#spring.ai.google.genai.embedding.api-key=AIzaSyCwDuKC5ziBtZrgxRJnzF2KlB9og_Ey26s
#spring.ai.google.genai.project-id=gen-lang-client-0149272138

spring.ai.model.chat=google-genai
spring.ai.model.embedding=google-genai

spring.ai.google.genai.api-key=AIzaSyCwDuKC5ziBtZrgxRJnzF2KlB9og_Ey26s
# Azure Data Explorer
adx.cluster-url=https://yourcluster.eastus.kusto.windows.net
adx.database=your-database-name
adx.client-id=YOUR_AZURE_APP_CLIENT_ID
adx.client-secret=YOUR_AZURE_APP_CLIENT_SECRET
adx.tenant-id=YOUR_AZURE_TENANT_ID

# Optional — limit rows returned to avoid huge LLM context
adx.max-rows=200


confluence.base-url=
confluence.username=
confluence.api-token=NCA9EeUcaQ7arJHTtX6iZ6CXwYWuDv7GwVugi31wpl-w=B663332B
confluence.space-key=DEV 
confluence.page-ids[0]=327681
#confluence.page-ids[1]=987654321
#confluence.page-ids[2]=112233445=========
# RAG DOCUMENT SOURCES
# =========================
# ---------- SOURCE 1 ----------
rag.sources[0].type=pdf
rag.sources[0].name=underwriting-guide
rag.sources[0].path=./docs/sample.pdf



# ---------- SOURCE 3 ----------
#rag.sources[1].type=confluence
#rag.sources[1].name=underwriting-wiki
#rag.sources[1].url=https://anilgupta00749.atlassian.net/wiki/spaces/SD/pages/327681/Testing+RAG

